# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aBWcamX0ImrAT0Ts6zOPcj-9Y8ZjJxc
"""

! pip install gtts

from gtts import gTTS
import os
text="Hello everyone, have a nice day!"
language="en"
tts=gTTS(text=text,lang=language,slow=False)
audio_file="speach.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="""Oh ma douce souffrance
Pourquoi s'acharner tu recommences
Je ne suis qu'un être sans importance
Sans lui je suis un peu paro'
Je déambule seule dans le métro
Une dernière danse
Pour oublier ma peine immense
Je veux m'enfuir que tout recommence
Oh ma douce souffrance

Je remue le ciel, le jour, la nuit
Je danse avec le vent la pluie
Un peu d'amour, un brin de miel
Et je danse, danse, danse,
Danse, danse, danse, danse
Et dans le bruit, je cours et j'ai peur
Est ce mon tour?
Vient la douleur...
Dans tout Paris, je m’abandonne
Et je m'envole, vole, vole, vole, vole, vole, vole"""

language="fr"
tts=gTTS(text=text,lang=language,slow=False)
audio_file="speach2.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="""Die Natur verändert sich jeden Tag,
und jeder Mensch erlebt sie auf seine eigene Weise.
Der Wind bewegt die Blätter der alten Bäume,
während die Sonne langsam hinter den Bergen verschwindet.
Viele Menschen finden in solchen Momenten Ruhe und Inspiration.
Die Welt wird oft als laut und hektisch beschrieben,
aber in der Natur kann man die wahre Stille fühlen.
Diese Stille ist nicht leer, sondern voller Bedeutung und Tiefe.
Sie erinnert uns daran,dass Zeit vergeht,
dass alles wächst und wieder verschwindet"""
languaage="de"
tts=gTTS(text=text,lang=language,slow=False)
audio_file="speach3.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text="""“Günlük hayat, insanların zihinlerinde sürekli hareket eden
düşüncelerle doludur. Her sabah uyanmak, yeni bir başlangıç
yapmak ve günün getireceği sorumluluklarla yüzleşmek çoğu insan için doğal
bir rutindir. Ancak bazı günler her şey daha ağır gelebilir.
İnsan psikolojisi, duyguların dengesine bağlıdır.
Mutluluk, kaygı, umut ve yorgunluk arasında gidip gelmek,
insanı hem güçlendirir hem de hayatın değerini anlamaya zorlar.
Kişi kendini ne kadar tanırsa,
karşılaştığı zorluklarla o kadar kolay başa çıkabilir"""
languaage="tr"
tts=gTTS(text=text,lang=languaage,slow=False)
audio_file="speach4.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)